#ifndef MAKEVIDEOSNAPSHOT_MVS_H
#define MAKEVIDEOSNAPSHOT_MVS_H

#define ERR_CODEC_PARAMETER (-256)
#define ERR_CODEC (-257)
#define ERR_CODEC_CONTEXT (-258)
#define ERR_PACKET (-259)
#define ERR_FRAME (-260)
#define ERR_BUFFER_SIZE (-261)
#define ERR_BUFFER (-262)
#define ERR_RGB_BUFFER_SIZE (-263)
#define ERR_RGB_BUFFER (-264)
#define ERR_SWS_CONTEXT (-265)
#define ERR_SWS_SCALE (-266)
#define ERR_WRITE_IMAGE (-267)
#define ERR_FILE_OPEN (-268)
#define ERR_LIBPNG_CWS (-269)
#define ERR_LIBPNG_CIS (-270)
#define ERR_LIBPNG_SETJMP (-271)

#define PIXEL_CHANNELS_COUNT_RGB 3 // RGB.
#define PIXEL_CHANNELS_COUNT_RGBA 4 // RGBA.

#define CODEC_LIBVPX_VP9 "libvpx-vp9"

#endif //MAKEVIDEOSNAPSHOT_MVS_H
