#ifndef MAKEVIDEOSNAPSHOT_MVS_H
#define MAKEVIDEOSNAPSHOT_MVS_H

#define ERR_CODEC_PARAMETER (-256)
#define ERR_CODEC (-257)
#define ERR_CODEC_CONTEXT (-258)
#define ERR_PACKET (-259)
#define ERR_BUFFER_SIZE (-260)
#define ERR_BUFFER (-261)
#define ERR_RGB_BUFFER_SIZE (-262)
#define ERR_RGB_BUFFER (-263)
#define ERR_SWS_CONTEXT (-264)
#define ERR_SWS_SCALE (-265)
#define ERR_WRITE_IMAGE (-266)
#define ERR_FILE_OPEN (-267)
#define ERR_LIBPNG_CWS (-268)
#define ERR_LIBPNG_CIS (-269)
#define ERR_LIBPNG_SETJMP (-270)

#define PIXEL_CHANNELS_COUNT 4 // RGBA.

#endif //MAKEVIDEOSNAPSHOT_MVS_H
